"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import EntityServicesManager from "../../../../components/EntityServicesManager";
import ClientMasterEditor from "./ClientMasterEditor";
import OfferEmailEditor from "./OfferEmailEditor";
import { getCustomer } from "../../../../../lib/customer-master";
import styles from "./record.module.css";

const nav=[["Control Tower","/dashboard"],["Decision Center","/dashboard/decision-center"],["Partidas","/dashboard/partidas"],["Expediciones","/dashboard/expediciones"],["Viajes","/dashboard/viajes"],["Ofertas y tarifas","/dashboard/ofertas-tarifas"],["Clientes","/dashboard/clientes"],["Colaboradores","/dashboard/colaboradores"],["Almacenes","/dashboard/almacenes"],["Tracking","/dashboard/tracking"],["ePOD & CMR","/dashboard/epod-cmr"],["Informes","/dashboard/informes"]] as const;

type Item=Record<string,unknown>;
export default function RecordEditor({module,id}:{module:string;id:string}){
 if(module==="clientes")return <div className={styles.clientStack}><ClientMasterEditor id={id}/><div className={styles.clientServices}><CustomerAdrSettings id={id}/><EntityServicesManager entityType="cliente" entityId={id}/></div></div>;
 if(module==="ofertas-tarifas"&&id!=="nuevo")return <OfferEmailEditor id={id}/>;
 return <GenericRecordEditor module={module} id={id}/>;
}

function CustomerAdrSettings({id}:{id:string}){
 const master=getCustomer(id);
 const [frequency,setFrequency]=useState<"NEVER"|"SOMETIMES"|"ALWAYS">(master?.adrControl==="S"?"SOMETIMES":"NEVER");
 const [policy,setPolicy]=useState<"INFO"|"WARNING"|"ACKNOWLEDGEMENT"|"BLOCKING">("WARNING");
 const [preferred,setPreferred]=useState<string[]>([]);
 const [message,setMessage]=useState("Cargando configuración…");
 const [saving,setSaving]=useState(false);
 useEffect(()=>{let active=true;fetch(`/api/customers/adr-profile?customerCode=${encodeURIComponent(id)}`,{cache:"no-store"}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error||"No se pudo cargar la configuración ADR.");if(!active)return;setFrequency(result.item.frequency);setPolicy(result.item.validationPolicy);setPreferred(result.item.preferredClasses||[]);setMessage("")}).catch(error=>active&&setMessage(error instanceof Error?error.message:"No se pudo cargar la configuración ADR."));return()=>{active=false}},[id]);
 function toggleClass(value:string){setPreferred(current=>current.includes(value)?current.filter(item=>item!==value):[...current,value])}
 async function save(){setSaving(true);setMessage("");try{const response=await fetch("/api/customers/adr-profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerCode:id,frequency,validationPolicy:policy,preferredClasses:preferred})});const result=await response.json();if(!response.ok)throw new Error(result.error||"No se pudo guardar la configuración ADR.");setMessage(`Configuración ADR auditada y guardada para ${id}.`)}catch(error){setMessage(error instanceof Error?error.message:"No se pudo guardar la configuración ADR.")}finally{setSaving(false)}}
 const classes=["1","2.1","2.2","2.3","3","4.1","4.2","4.3","5.1","5.2","6.1","6.2","7","8","9"];
 return <section className={styles.card}><h2>Control ADR</h2><p>Define el comportamiento inicial de los pedidos. Las clases habituales solo priorizan búsquedas: nunca restringen la clasificación real.</p><div className={styles.grid}><label>Frecuencia ADR<select value={frequency} onChange={e=>setFrequency(e.target.value as typeof frequency)}><option value="NEVER">Nunca · No premarcado</option><option value="SOMETIMES">A veces · Exigir decisión</option><option value="ALWAYS">Siempre · Sí premarcado</option></select></label><label>Tratamiento de incidencias<select value={policy} onChange={e=>setPolicy(e.target.value as typeof policy)}><option value="INFO">Información</option><option value="WARNING">Advertencia</option><option value="ACKNOWLEDGEMENT">Advertencia con confirmación</option><option value="BLOCKING">Bloqueo</option></select></label></div><div><p>Clases habituales</p><div style={{display:"flex",flexWrap:"wrap",gap:8}}>{classes.map(value=><button key={value} type="button" onClick={()=>toggleClass(value)} aria-pressed={preferred.includes(value)} style={{border:"1px solid #cbd6e2",borderRadius:999,padding:"7px 10px",background:preferred.includes(value)?"#0b6797":"#fff",color:preferred.includes(value)?"#fff":"#30465f",fontWeight:700}}>Clase {value}</button>)}</div></div><div className={styles.submit}><button type="button" onClick={save} disabled={saving}>{saving?"Guardando…":"Guardar configuración ADR"}</button></div>{message&&<p className={styles.message}>{message}</p>}</section>;
}

function GenericRecordEditor({module,id}:{module:string;id:string}){
 const [item,setItem]=useState<Item>({id:id==="nuevo"?"":id});
 const [message,setMessage]=useState("");
 useEffect(()=>{const list=JSON.parse(localStorage.getItem(`fornexa-${module}`)||"[]") as Item[];const found=list.find(x=>String(x.id||x.nombre||x.referencia)===id);if(found)setItem(found);},[module,id]);
 function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const nextItem:Object={...item,id:String(fd.get("id")||item.id||`${module.slice(0,2).toUpperCase()}-${String(Date.now()).slice(-6)}`),nombre:String(fd.get("nombre")||""),estado:String(fd.get("estado")||"Activo"),clienteId:String(fd.get("clienteId")||""),colaboradorId:String(fd.get("colaboradorId")||""),expedicionId:String(fd.get("expedicionId")||""),viajeId:String(fd.get("viajeId")||""),notas:String(fd.get("notas")||"")};const list=JSON.parse(localStorage.getItem(`fornexa-${module}`)||"[]") as Item[];const key=String((nextItem as Item).id);const filtered=list.filter(x=>String(x.id)!==key);localStorage.setItem(`fornexa-${module}`,JSON.stringify([nextItem,...filtered]));setItem(nextItem as Item);setMessage("Registro guardado. Las referencias se han conservado como relaciones por ID.");}
 return <main className={styles.shell}><aside className={styles.sidebar}><Link href="/dashboard" className={styles.brand}>FORNEXA</Link><nav className={styles.nav}>{nav.map(([l,h])=><Link key={h} href={h}>{l}</Link>)}</nav><div className={styles.footer}>FORNEXA Suite<small>Editor relacional</small></div></aside><section className={styles.content}><header><div><p>{module==="colaboradores"?"PROVEEDOR · RED LOGÍSTICA":"REGISTRO RELACIONAL"}</p><h1>{id==="nuevo"?`Nuevo registro de ${module}`:id}</h1><span>{module==="colaboradores"?"Datos del proveedor, relaciones y servicios ofrecidos en una única ficha.":"Edición y persistencia local del registro y de sus relaciones operativas."}</span></div><div className={styles.actions}><Link href={`/dashboard/importar?entidad=${module}`}>Importar Excel</Link><Link href={`/dashboard/${module}`}>Volver</Link></div></header><form onSubmit={save}><section className={styles.card}><h2>Datos generales</h2><div className={styles.grid}><label>ID<input name="id" defaultValue={String(item.id||"")} placeholder="Se genera automáticamente"/></label><label>Nombre / descripción<input name="nombre" defaultValue={String(item.nombre||"")}/></label><label>Estado<select name="estado" defaultValue={String(item.estado||"Activo")}><option>Activo</option><option>Planificado</option><option>Pendiente</option><option>Cerrado</option></select></label></div></section><section className={styles.card}><h2>Relaciones</h2><p>Introduce el ID existente. Estas claves permiten navegar y consolidar datos entre módulos.</p><div className={styles.grid}><label>Cliente relacionado<input name="clienteId" defaultValue={String(item.clienteId||"")} placeholder="CL-..."/></label><label>Colaborador relacionado<input name="colaboradorId" defaultValue={String(item.colaboradorId||"")} placeholder="CO-..."/></label><label>Expedición relacionada<input name="expedicionId" defaultValue={String(item.expedicionId||"")} placeholder="EX-..."/></label><label>Viaje relacionado<input name="viajeId" defaultValue={String(item.viajeId||"")} placeholder="VJ-..."/></label></div></section>{module==="colaboradores"&&<EntityServicesManager entityType="proveedor" entityId={id}/>}<section className={styles.card}><label>Notas<textarea name="notas" defaultValue={String(item.notas||"")} rows={5}/></label></section>{message&&<p className={styles.message}>{message}</p>}<div className={styles.submit}><Link href={`/dashboard/${module}`}>Cancelar</Link><button type="submit">Guardar registro</button></div></form></section></main>;
}
