"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import OfferEmailEditor from "./OfferEmailEditor";
import styles from "./record.module.css";

const nav=[["Control Tower","/dashboard"],["Decision Center","/dashboard/decision-center"],["Partidas","/dashboard/partidas"],["Expediciones","/dashboard/expediciones"],["Viajes","/dashboard/viajes"],["Ofertas y tarifas","/dashboard/ofertas-tarifas"],["Clientes","/dashboard/clientes"],["Colaboradores","/dashboard/colaboradores"],["Almacenes","/dashboard/almacenes"],["Tracking","/dashboard/tracking"],["ePOD & CMR","/dashboard/epod-cmr"],["Informes","/dashboard/informes"]] as const;

type Item=Record<string,unknown>;
export default function RecordEditor({module,id}:{module:string;id:string}){
 if(module==="ofertas-tarifas"&&id!=="nuevo")return <OfferEmailEditor id={id}/>;
 const [item,setItem]=useState<Item>({id:id==="nuevo"?"":id});
 const [message,setMessage]=useState("");
 useEffect(()=>{const list=JSON.parse(localStorage.getItem(`fornexa-${module}`)||"[]") as Item[];const found=list.find(x=>String(x.id||x.nombre||x.referencia)===id);if(found)setItem(found);},[module,id]);
 function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const nextItem:Object={...item,id:String(fd.get("id")||item.id||`${module.slice(0,2).toUpperCase()}-${String(Date.now()).slice(-6)}`),nombre:String(fd.get("nombre")||""),estado:String(fd.get("estado")||"Activo"),clienteId:String(fd.get("clienteId")||""),colaboradorId:String(fd.get("colaboradorId")||""),expedicionId:String(fd.get("expedicionId")||""),viajeId:String(fd.get("viajeId")||""),notas:String(fd.get("notas")||"")};const list=JSON.parse(localStorage.getItem(`fornexa-${module}`)||"[]") as Item[];const key=String((nextItem as Item).id);const filtered=list.filter(x=>String(x.id)!==key);localStorage.setItem(`fornexa-${module}`,JSON.stringify([nextItem,...filtered]));setItem(nextItem as Item);setMessage("Registro guardado. Las referencias se han conservado como relaciones por ID.");}
 return <main className={styles.shell}><aside className={styles.sidebar}><Link href="/dashboard" className={styles.brand}>FORNEXA</Link><nav className={styles.nav}>{nav.map(([l,h])=><Link key={h} href={h}>{l}</Link>)}</nav><div className={styles.footer}>FORNEXA Suite<small>Editor relacional</small></div></aside><section className={styles.content}><header><div><p>REGISTRO RELACIONAL</p><h1>{id==="nuevo"?`Nuevo registro de ${module}`:id}</h1><span>Edición y persistencia local del registro y de sus relaciones operativas.</span></div><div className={styles.actions}><Link href={`/dashboard/importar?entidad=${module}`}>Importar Excel</Link><Link href={`/dashboard/${module}`}>Volver</Link></div></header><form onSubmit={save}><section className={styles.card}><h2>Datos generales</h2><div className={styles.grid}><label>ID<input name="id" defaultValue={String(item.id||"")} placeholder="Se genera automáticamente"/></label><label>Nombre / descripción<input name="nombre" defaultValue={String(item.nombre||"")}/></label><label>Estado<select name="estado" defaultValue={String(item.estado||"Activo")}><option>Activo</option><option>Planificado</option><option>Pendiente</option><option>Cerrado</option></select></label></div></section><section className={styles.card}><h2>Relaciones</h2><p>Introduce el ID existente. Estas claves permiten navegar y consolidar datos entre módulos.</p><div className={styles.grid}><label>Cliente relacionado<input name="clienteId" defaultValue={String(item.clienteId||"")} placeholder="CL-..."/></label><label>Colaborador relacionado<input name="colaboradorId" defaultValue={String(item.colaboradorId||"")} placeholder="CO-..."/></label><label>Expedición relacionada<input name="expedicionId" defaultValue={String(item.expedicionId||"")} placeholder="EX-..."/></label><label>Viaje relacionado<input name="viajeId" defaultValue={String(item.viajeId||"")} placeholder="VJ-..."/></label></div></section><section className={styles.card}><label>Notas<textarea name="notas" defaultValue={String(item.notas||"")} rows={5}/></label></section>{message&&<p className={styles.message}>{message}</p>}<div className={styles.submit}><Link href={`/dashboard/${module}`}>Cancelar</Link><button type="submit">Guardar registro</button></div></form></section></main>;
}
