"use client";

import Link from "next/link";
import { ChangeEvent, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import styles from "./import.module.css";

type Entity = "partidas" | "expediciones" | "viajes" | "clientes" | "colaboradores";
type Row = Record<string, unknown>;

const nav = [["Control Tower","/dashboard"],["Decision Center","/dashboard/decision-center"],["Partidas","/dashboard/partidas"],["Expediciones","/dashboard/expediciones"],["Viajes","/dashboard/viajes"],["Ofertas y tarifas","/dashboard/ofertas-tarifas"],["Clientes","/dashboard/clientes"],["Colaboradores","/dashboard/colaboradores"],["Almacenes","/dashboard/almacenes"],["Tracking","/dashboard/tracking"],["ePOD & CMR","/dashboard/epod-cmr"],["Informes","/dashboard/informes"]] as const;

const schema: Record<Entity,{label:string; fields:{key:string;label:string;required?:boolean;relation?:string}[]}>= {
 partidas:{label:"Partidas",fields:[{key:"id",label:"ID"},{key:"cliente",label:"Cliente",required:true,relation:"clientes"},{key:"origen",label:"Origen",required:true},{key:"destino",label:"Destino",required:true},{key:"bultos",label:"Bultos"},{key:"peso",label:"Peso (kg)"},{key:"servicio",label:"Servicio"},{key:"expedicionId",label:"Expedición relacionada",relation:"expediciones"},{key:"estado",label:"Estado"}]},
 expediciones:{label:"Expediciones",fields:[{key:"id",label:"ID"},{key:"origen",label:"Origen",required:true},{key:"destino",label:"Destino",required:true},{key:"servicio",label:"Servicio"},{key:"fecha",label:"Fecha"},{key:"partidas",label:"IDs de partidas",relation:"partidas"},{key:"viajeId",label:"Viaje relacionado",relation:"viajes"},{key:"estado",label:"Estado"}]},
 viajes:{label:"Viajes",fields:[{key:"id",label:"ID"},{key:"fecha",label:"Fecha"},{key:"vehiculo",label:"Vehículo"},{key:"conductor",label:"Conductor"},{key:"expediciones",label:"IDs de expediciones",relation:"expediciones"},{key:"estado",label:"Estado"}]},
 clientes:{label:"Clientes",fields:[{key:"id",label:"ID"},{key:"nombre",label:"Nombre",required:true},{key:"cif",label:"CIF"},{key:"ciudad",label:"Ciudad"},{key:"contacto",label:"Contacto"},{key:"email",label:"Email"},{key:"estado",label:"Estado"}]},
 colaboradores:{label:"Colaboradores",fields:[{key:"id",label:"ID"},{key:"nombre",label:"Nombre",required:true},{key:"tipo",label:"Tipo"},{key:"cobertura",label:"Cobertura"},{key:"capacidad",label:"Capacidad"},{key:"valoracion",label:"Valoración"},{key:"estado",label:"Estado"}]}
};

const prefix:Record<Entity,string>={partidas:"PT",expediciones:"EX",viajes:"VJ",clientes:"CL",colaboradores:"CO"};

export default function ImportPage(){
 const [entity,setEntity]=useState<Entity>("partidas");
 const [selected,setSelected]=useState<string[]>(schema.partidas.fields.map(f=>f.key));
 const [rows,setRows]=useState<Row[]>([]);
 const [headers,setHeaders]=useState<string[]>([]);
 const [mapping,setMapping]=useState<Record<string,string>>({});
 const [message,setMessage]=useState("");
 const fields=schema[entity].fields;
 const selectedFields=useMemo(()=>fields.filter(f=>selected.includes(f.key)),[fields,selected]);
 function changeEntity(next:Entity){setEntity(next);setSelected(schema[next].fields.map(f=>f.key));setRows([]);setHeaders([]);setMapping({});setMessage("");}
 function toggle(key:string){setSelected(v=>v.includes(key)?v.filter(x=>x!==key):[...v,key]);}
 function downloadTemplate(){const sample:Row={};selectedFields.forEach(f=>sample[f.label]=f.relation?"ID relacionado":"");const ws=XLSX.utils.json_to_sheet([sample]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,schema[entity].label);XLSX.writeFile(wb,`FORNEXA_${entity}_plantilla.xlsx`);}
 async function loadFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const data=await file.arrayBuffer();const wb=XLSX.read(data);const ws=wb.Sheets[wb.SheetNames[0]];const parsed=XLSX.utils.sheet_to_json<Row>(ws,{defval:""});const hs=parsed.length?Object.keys(parsed[0]):[];setRows(parsed);setHeaders(hs);const auto:Record<string,string>={};selectedFields.forEach(f=>{const hit=hs.find(h=>h.toLowerCase()===f.label.toLowerCase()||h.toLowerCase()===f.key.toLowerCase());if(hit)auto[f.key]=hit;});setMapping(auto);setMessage(`${parsed.length} fila(s) leídas. Revisa la correspondencia antes de importar.`);}
 function importRows(){if(!rows.length){setMessage("Carga primero un fichero Excel.");return;}const missing=selectedFields.filter(f=>f.required&&!mapping[f.key]);if(missing.length){setMessage(`Falta mapear: ${missing.map(x=>x.label).join(", ")}.`);return;}const current=JSON.parse(localStorage.getItem(`fornexa-${entity}`)||"[]");const imported=rows.map((r,i)=>{const item:Record<string,unknown>={};selectedFields.forEach(f=>{const source=mapping[f.key];let value:unknown=source?r[source]:"";if((f.key==="partidas"||f.key==="expediciones")&&typeof value==="string")value=value.split(/[,;|]/).map(x=>x.trim()).filter(Boolean);item[f.key]=value;});if(!item.id)item.id=`${prefix[entity]}-${String(Date.now()+i).slice(-6)}`;if(!item.estado)item.estado="Importado";return item;});localStorage.setItem(`fornexa-${entity}`,JSON.stringify([...imported,...current]));setMessage(`${imported.length} registro(s) importados y guardados en ${schema[entity].label}. Las referencias se conservaron como relaciones por ID.`);}
 return <main className={styles.shell}><aside className={styles.sidebar}><Link href="/dashboard" className={styles.brand}>FORNEXA</Link><nav className={styles.nav}>{nav.map(([l,h])=><Link key={h} href={h}>{l}</Link>)}</nav><div className={styles.footer}>FORNEXA Suite<small>Importación estructurada</small></div></aside><section className={styles.content}><header className={styles.header}><div><p>DATA ONBOARDING</p><h1>Importar desde Excel</h1><span>Selecciona la entidad y los campos de FORNEXA. Después descarga nuestra plantilla o asigna las columnas de un Excel existente.</span></div><Link className={styles.back} href={`/dashboard/${entity}`}>Volver al módulo</Link></header><section className={styles.steps}><article><b>1</b><span>Entidad</span></article><article><b>2</b><span>Campos</span></article><article><b>3</b><span>Mapeo</span></article><article><b>4</b><span>Importación</span></article></section><section className={styles.card}><h2>1. Estructura de destino</h2><div className={styles.entities}>{(Object.keys(schema) as Entity[]).map(k=><button key={k} className={entity===k?styles.active:""} onClick={()=>changeEntity(k)}>{schema[k].label}</button>)}</div></section><section className={styles.card}><div className={styles.cardHead}><div><h2>2. Campos que desea agregar</h2><p>Los campos relacionales se enlazan mediante el ID del registro relacionado.</p></div><button onClick={downloadTemplate}>Descargar plantilla Excel</button></div><div className={styles.fields}>{fields.map(f=><label key={f.key} className={selected.includes(f.key)?styles.selected:""}><input type="checkbox" checked={selected.includes(f.key)} onChange={()=>toggle(f.key)}/><span><b>{f.label}</b>{f.relation&&<small>Relación con {f.relation}</small>}</span>{f.required&&<em>Obligatorio</em>}</label>)}</div></section><section className={styles.card}><h2>3. Cargar y asignar columnas</h2><label className={styles.upload}>Seleccionar fichero .xlsx o .xls<input type="file" accept=".xlsx,.xls" onChange={loadFile}/></label>{headers.length>0&&<div className={styles.mapping}>{selectedFields.map(f=><label key={f.key}><span>{f.label}{f.required?" *":""}</span><select value={mapping[f.key]||""} onChange={e=>setMapping({...mapping,[f.key]:e.target.value})}><option value="">No importar</option>{headers.map(h=><option key={h}>{h}</option>)}</select></label>)}</div>}</section><section className={styles.card}><div className={styles.cardHead}><div><h2>4. Validar e importar</h2><p>{rows.length?`${rows.length} filas preparadas`:`Todavía no hay datos cargados`}</p></div><button onClick={importRows} disabled={!rows.length}>Importar y guardar</button></div>{message&&<p className={styles.message}>{message}</p>}</section></section></main>;
}
