"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { useParams, useSearchParams } from "next/navigation";
import { companyMaster } from "../../../lib/company-master";
import styles from "./cmr-document.module.css";

type GoodsLine={marks:string;packages:string;packaging:string;description:string;statisticalNumber:string;weight:string;volume:string;adr?:{declared?:boolean;unNumber?:string;class?:string;labels?:string;packingGroup?:string;tunnelCode?:string;description?:string}};
type SuccessiveCarrier={name:string;taxId?:string;address?:string;country?:string};
type Attachment={title:string;type?:string;reference?:string};
type CmrView={expedicion:string;viaje:string;fecha:string;estado:string;remitente:string;remitenteDireccion:string;destinatario:string;destinatarioDireccion:string;carga:string;entrega:string;transportista:string;tractor:string;remolque:string;goodsLines:GoodsLine[];senderInstructions:string;carrierReservations:string;particularTerms:string;attachedDocuments:Attachment[];successiveCarriers:SuccessiveCarrier[];carriageCharges:string;cashOnDelivery:string;established:string;firmas:string};

export default function CmrDocumentPage(){
 const params=useParams<{cmr:string}>(),searchParams=useSearchParams(),didPrint=useRef(false);
 const cmr=decodeURIComponent(params.cmr),sharedKey=searchParams.get("key")??"";
 const [doc,setDoc]=useState<CmrView|null>(null),[ready,setReady]=useState(false),[isLive,setIsLive]=useState(false),[accessKey,setAccessKey]=useState(""),[qrStatus,setQrStatus]=useState<{src:string;state:"ready"|"error"}|null>(null);
 const qrSrc=isLive?(accessKey?`/api/cmr/${encodeURIComponent(cmr)}/qr?key=${encodeURIComponent(accessKey)}`:`/api/cmr/${encodeURIComponent(cmr)}/qr`):"";
 const qrState=qrStatus?.src===qrSrc?qrStatus.state:"loading";
 const exportPdf=useCallback(()=>{if(!doc||!isLive||qrState!=="ready")return;const previousTitle=document.title;document.title=`${cmr}-${doc.expedicion}`;window.print();window.setTimeout(()=>{document.title=previousTitle},500)},[cmr,doc,isLive,qrState]);

 useEffect(()=>{
  let cancelled=false;
  async function refresh(){try{const localDocuments=JSON.parse(localStorage.getItem("fornexa-cmr-documents")||"[]") as Array<{id?:string;cmrNumber?:string;cmrKey?:string}>;const localKey=localDocuments.find(item=>item.id===cmr||item.cmrNumber===cmr)?.cmrKey??"";const key=sharedKey||localKey;if(key)setAccessKey(key);const headers:Record<string,string>={};if(key)headers["x-fornexa-key"]=key;const response=await fetch(`/api/cmr/${encodeURIComponent(cmr)}`,{cache:"no-store",headers,credentials:"same-origin"});if(!response.ok){setDoc(null);setReady(true);return}const result=await response.json();if(cancelled)return;const item=result.document,events=Array.isArray(result.events)?result.events:[];const meta=(item.metadata&&typeof item.metadata==="object"?item.metadata:{}) as Record<string,unknown>;const cmrMeta=(meta.cmr&&typeof meta.cmr==="object"?meta.cmr:{}) as Record<string,unknown>;const signatures=events.filter((event:{event_type:string})=>event.event_type==="signature_added").length;setDoc({expedicion:item.expedition_id||"—",viaje:item.trip_id||"—",fecha:new Date(item.issued_at).toLocaleDateString("es-ES"),estado:item.status,remitente:item.sender,remitenteDireccion:item.pickup_location,destinatario:item.recipient,destinatarioDireccion:item.delivery_location,carga:item.pickup_location,entrega:item.delivery_location,transportista:item.carrier,tractor:item.vehicle_registration||"—",remolque:item.trailer_registration||"—",goodsLines:readGoodsLines(cmrMeta,item),senderInstructions:text(cmrMeta.senderInstructions)||item.instructions||"Sin instrucciones particulares",carrierReservations:text(cmrMeta.carrierReservations)||"Sin reservas",particularTerms:text(cmrMeta.particularTerms)||"Sin estipulaciones particulares",attachedDocuments:readAttachments(cmrMeta.attachedDocuments),successiveCarriers:readCarriers(cmrMeta.successiveCarriers),carriageCharges:objectSummary(cmrMeta.carriageCharges,"Según acuerdo comercial"),cashOnDelivery:objectSummary(cmrMeta.cashOnDelivery,"Sin reembolso"),established:[text(cmrMeta.establishedAt),text(cmrMeta.establishedOn)].filter(Boolean).join(" · ")||new Date(item.issued_at).toLocaleDateString("es-ES"),firmas:signatures?`${signatures} firma(s) electrónica(s) registrada(s).`:"Pendiente de completar firmas."});setIsLive(true);setReady(true)}catch{if(!cancelled){setDoc(null);setReady(true)}}}
  refresh();const timer=window.setInterval(refresh,15000);return()=>{cancelled=true;window.clearInterval(timer)};
 },[cmr,sharedKey]);
 useEffect(()=>{if(ready&&doc&&isLive&&qrState==="ready"&&searchParams.get("print")==="1"&&!didPrint.current){didPrint.current=true;window.setTimeout(()=>exportPdf(),50)}},[ready,doc,isLive,qrState,searchParams,exportPdf]);

 if(!ready)return <CmrStatus message="Cargando CMR…"/>;
 if(!doc)return <CmrStatus message="CMR no disponible. El documento no existe o la clave/sesión de acceso no es válida."/>;

 const adrLines=doc.goodsLines.filter(line=>line.adr?.declared||line.adr?.unNumber||line.adr?.class);

 return <main className={styles.page}>
  <header className={styles.appHeader}><div><Link href="/dashboard/epod-cmr" className={styles.back}>← ePOD & CMR</Link><h1>{cmr}</h1><p>{doc.expedicion} · {doc.viaje} · {doc.estado}</p>{qrState==="error"?<p className={styles.qrNotice} role="alert">El acceso QR no está vigente. Renueva la capability antes de imprimir o exportar.</p>:null}</div><div className={styles.actions}><button type="button" className={styles.secondary} onClick={exportPdf} disabled={qrState!=="ready"}>{qrState==="loading"?"Preparando QR…":"Imprimir"}</button><button type="button" className={styles.primary} onClick={exportPdf} disabled={qrState!=="ready"}>{qrState==="loading"?"Preparando QR…":"Exportar PDF"}</button></div></header>
  <section className={styles.paper}>
   <div className={styles.paperHeader}><div><strong>CARTA DE PORTE INTERNACIONAL</strong><span>Convention relative au contrat de transport international de marchandises par route (CMR)</span></div><div className={styles.documentNumber}><span>N.º CMR</span><strong>{cmr}</strong>{isLive&&qrState!=="error"?<img className={qrState==="ready"?styles.qrReady:styles.qrPending} src={qrSrc} alt={`QR ${cmr}`} onLoad={()=>setQrStatus({src:qrSrc,state:"ready"})} onError={()=>setQrStatus({src:qrSrc,state:"error"})}/>:null}{isLive&&qrState!=="ready"?<span className={styles.qrStatus}>{qrState==="error"?"QR no vigente":"Preparando QR"}</span>:null}</div></div>
   <div className={styles.gridTwo}>
    <article><span className={styles.boxNumber}>1</span><h2>Expedidor</h2><strong>{doc.remitente}</strong><p>{doc.remitenteDireccion}</p></article><article><span className={styles.boxNumber}>16</span><h2>Transportista</h2><strong>{doc.transportista}</strong><p>Tractor: {doc.tractor}<br/>Remolque: {doc.remolque}</p></article>
    <article><span className={styles.boxNumber}>2</span><h2>Destinatario</h2><strong>{doc.destinatario}</strong><p>{doc.destinatarioDireccion}</p></article><article><span className={styles.boxNumber}>17</span><h2>Transportistas sucesivos</h2><p>{doc.successiveCarriers.length?doc.successiveCarriers.map((carrier,index)=><span key={`${carrier.name}-${index}`}>{carrier.name}{carrier.taxId?` · ${carrier.taxId}`:""}{carrier.address?<><br/>{carrier.address}</>:null}<br/></span>):"No declarados"}</p></article>
    <article><span className={styles.boxNumber}>3</span><h2>Lugar previsto para la entrega</h2><p>{doc.entrega}</p></article><article><span className={styles.boxNumber}>18</span><h2>Reservas y observaciones del transportista</h2><p>{doc.carrierReservations}</p></article>
    <article><span className={styles.boxNumber}>4</span><h2>Lugar y fecha de carga</h2><p>{doc.carga}</p></article><article><span className={styles.boxNumber}>19</span><h2>Estipulaciones particulares</h2><p>{doc.particularTerms}</p></article>
    <article><span className={styles.boxNumber}>5</span><h2>Documentos anexos</h2><p>{doc.attachedDocuments.length?doc.attachedDocuments.map((item,index)=><span key={`${item.title}-${index}`}>{item.title}{item.reference?` · ${item.reference}`:""}<br/></span>):"Sin documentos anexos declarados"}</p></article><article><span className={styles.boxNumber}>20</span><h2>Gastos / portes</h2><p>{doc.carriageCharges}</p></article>
   </div>
   <section className={styles.goods}><div className={styles.goodsHead}><span>6 Marcas y números</span><span>7 Nº bultos</span><span>8 Embalaje</span><span>9 Naturaleza</span><span>10 N.º estadístico</span><span>11 Peso bruto</span><span>12 Volumen</span></div>{doc.goodsLines.map((line,index)=><div className={styles.goodsRow} key={`${line.marks}-${index}`}><span>{line.marks}</span><span>{line.packages}</span><span>{line.packaging}</span><span>{line.description}</span><span>{line.statisticalNumber}</span><span>{line.weight}</span><span>{line.volume}</span></div>)}</section>
   {adrLines.length?<section className={styles.adrBox}><strong>MERCANCÍA PELIGROSA (ADR)</strong>{adrLines.map((line,index)=><p key={`${line.adr?.unNumber}-${index}`}>ONU {line.adr?.unNumber||"—"} · Clase {line.adr?.class||"—"} · Etiquetas {line.adr?.labels||"—"} · Grupo embalaje {line.adr?.packingGroup||"—"}{line.adr?.tunnelCode?` · Túnel ${line.adr.tunnelCode}`:""}{line.adr?.description?` · ${line.adr.description}`:""}</p>)}</section>:null}
   <div className={styles.gridTwoBottom}><article><span className={styles.boxNumber}>13</span><h2>Instrucciones del remitente</h2><p>{doc.senderInstructions}</p></article><article><span className={styles.boxNumber}>14</span><h2>Instrucciones de pago / portes</h2><p>{doc.carriageCharges}</p></article><article><span className={styles.boxNumber}>15</span><h2>Reembolso</h2><p>{doc.cashOnDelivery}</p></article><article><span className={styles.boxNumber}>21</span><h2>Formalizado en / fecha</h2><p>{doc.established}</p></article></div>
   <section className={styles.signatures}><article><span>22</span><h2>Firma y sello del expedidor</h2><div className={styles.stamp} aria-label={`Sello de ${companyMaster.legalName}`}><strong>{companyMaster.cmrStamp.title}</strong><b>{companyMaster.cmrStamp.legalName}</b><small>{companyMaster.cmrStamp.taxId}</small><small>{companyMaster.cmrStamp.location}</small><em>{companyMaster.cmrStamp.registration}</em></div></article><article><span>23</span><h2>Firma y sello del transportista</h2><div className={styles.signatureState}>Firma electrónica registrada en trazabilidad</div></article><article><span>24</span><h2>Recibo de la mercancía / destinatario</h2><div className={styles.signatureState}>{doc.firmas}</div></article></section>
   <footer className={styles.paperFooter}><span>Generado por {companyMaster.tradeName} · Documento electrónico con trazabilidad</span><span>{doc.fecha} · {cmr}</span></footer>
  </section>
 </main>
}

function CmrStatus({message}:{message:string}){
 return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",padding:24,background:"#eef3f9"}}><section style={{maxWidth:560,padding:28,borderRadius:16,background:"white",border:"1px solid #dbe4ef",fontFamily:"Arial, sans-serif",color:"#172033"}}>{message}</section></main>
}

function readGoodsLines(meta:Record<string,unknown>,item:Record<string,unknown>):GoodsLine[]{
 const source=Array.isArray(meta.goodsLines)?meta.goodsLines:[];
 if(source.length)return source.map((raw)=>{const line=(raw&&typeof raw==="object"?raw:{}) as Record<string,unknown>;const adr=(line.adr&&typeof line.adr==="object"?line.adr:{}) as Record<string,unknown>;return{marks:text(line.marks)||String(item.expedition_id||item.cmr_number||"—"),packages:numberText(line.packages),packaging:text(line.packaging)||"—",description:text(line.description)||"—",statisticalNumber:text(line.statisticalNumber)||"—",weight:unit(line.weight,"kg"),volume:unit(line.volume,"m³"),adr:{declared:Boolean(adr.declared),unNumber:text(adr.unNumber),class:text(adr.class),labels:text(adr.labels),packingGroup:text(adr.packingGroup),tunnelCode:text(adr.tunnelCode),description:text(adr.description)}}});
 const adr=(item.adr&&typeof item.adr==="object"?item.adr:{}) as Record<string,unknown>;
 return[{marks:String(item.expedition_id||item.cmr_number||"—"),packages:numberText(item.packages),packaging:text(item.packaging)||"—",description:text(item.goods_description)||"—",statisticalNumber:"—",weight:unit(item.gross_weight,"kg"),volume:unit(item.volume,"m³"),adr:{declared:text(adr.declared)==="S",unNumber:text(adr.unNumber),class:text(adr.class),labels:text(adr.labels),packingGroup:text(adr.packingGroup),tunnelCode:text(adr.tunnelCode),description:text(adr.description)}}];
}
function readAttachments(value:unknown):Attachment[]{return Array.isArray(value)?value.map(raw=>{const item=(raw&&typeof raw==="object"?raw:{}) as Record<string,unknown>;return{title:text(item.title),type:text(item.type),reference:text(item.reference)}}).filter(item=>item.title):[]}
function readCarriers(value:unknown):SuccessiveCarrier[]{return Array.isArray(value)?value.map(raw=>{const item=(raw&&typeof raw==="object"?raw:{}) as Record<string,unknown>;return{name:text(item.name),taxId:text(item.taxId),address:text(item.address),country:text(item.country)}}).filter(item=>item.name):[]}
function objectSummary(value:unknown,fallbackValue:string){if(!value||typeof value!=="object"||Array.isArray(value))return fallbackValue;const entries=Object.entries(value as Record<string,unknown>).filter(([,v])=>String(v??"").trim());return entries.length?entries.map(([key,v])=>`${key}: ${String(v)}`).join(" · "):fallbackValue}
function text(value:unknown){return String(value??"").trim()}
function numberText(value:unknown){const n=Number(value);return Number.isFinite(n)&&n!==0?n.toLocaleString("es-ES"):text(value)||"—"}
function unit(value:unknown,suffix:string){const n=Number(value);return Number.isFinite(n)&&n!==0?`${n.toLocaleString("es-ES")} ${suffix}`:text(value)||"—"}
