import Link from "next/link";
import { notFound } from "next/navigation";
import DataGrid from "../../components/DataGrid";
import { MetricGrid, ScreenHeader, screenButton, screenPanelClass } from "../../components/ScreenChrome";
import styles from "./module.module.css";

const modules = {
 partidas:{eyebrow:"OPERATIVA",title:"Órdenes",description:"Pedidos de cliente grabados en FORNEXA. Una orden debe incorporarse a una expedición antes de poder viajar.",action:"+ Nueva orden",stats:[["24","Abiertas"],["8","Pendientes de expedición"],["3","Con incidencia"]],columns:["ID","Cliente","Origen / destino","Mercancía","Estado"],rows:[["PT-260184","Mediterránea Retail","Valencia → Lyon","2 palets · 840 kg","Preparada"],["PT-260183","Nova Distribution","Barcelona → Marseille","4 palets · 1.240 kg","Pendiente"],["PT-260182","Atlas Components","Madrid → Toulouse","1 palet ADR","Asignada"]]},
 expediciones:{eyebrow:"CONSOLIDACIÓN",title:"Expediciones",description:"Agrupaciones de una o varias partidas compatibles por ruta, servicio y planificación.",action:"+ Nueva expedición",stats:[["12","Activas"],["31","Partidas agrupadas"],["89%","Ocupación media"]],columns:["ID","Ruta","Partidas","Servicio","Estado"],rows:[["EX-260071","Valencia → Lyon","3 partidas","Grupaje","En tránsito"],["EX-260070","Barcelona → Marseille","2 partidas","LTL","Planificada"],["EX-260069","Madrid → Toulouse","1 partida","Directo","Entregada"]]},
 viajes:{eyebrow:"TRANSPORTE",title:"Viajes",description:"Cada viaje contiene una o varias expediciones. Nunca admite partidas sueltas.",action:"+ Nuevo viaje",stats:[["7","En curso"],["4","Planificados hoy"],["92%","Puntualidad"]],columns:["ID","Expediciones","Vehículo","Conductor","Estado"],rows:[["VJ-260041","EX-260071 · EX-260072","1234 LBC","J. Martínez","En ruta"],["VJ-260040","EX-260070","5678 MNP","P. García","Carga prevista"],["VJ-260039","EX-260069","9012 RST","L. Bernard","Finalizado"]]},
 "ofertas-tarifas":{eyebrow:"COMERCIAL",title:"Ofertas y tarifas",description:"Cotización, comparación de servicios, vigencias y control de rentabilidad.",action:"+ Nueva oferta",stats:[],columns:["Referencia","Cliente","Ruta","Importe","Estado"],rows:[]},
 clientes:{eyebrow:"CRM",title:"Clientes",description:"Fichas comerciales, contactos, direcciones, condiciones y actividad logística.",action:"+ Nuevo cliente",stats:[["146","Clientes activos"],["12","Oportunidades"],["4","Revisiones pendientes"]],columns:["Cliente","Ciudad","Contacto","Expediciones","Estado"],rows:[["Mediterránea Retail","Valencia","Laura Pérez","28","Activo"],["Nova Distribution","Barcelona","Marc Vidal","17","Activo"],["Atlas Components","Madrid","Ana Torres","9","Revisión"]]},
 colaboradores:{eyebrow:"RED LOGÍSTICA",title:"Colaboradores",description:"Transportistas, almacenes, agentes y proveedores con capacidad, cobertura y valoración.",action:"+ Nuevo colaborador",stats:[["63","Disponibles"],["11","En ruta"],["4,6/5","Valoración media"]],columns:["Colaborador","Tipo","Cobertura","Capacidad","Valoración"],rows:[["Velocity Transinternacional","Transportista","Nacional · Internacional · Baleares","Tráiler · Rígidos · Furgón","Tarifa 2026"],["Transports Rhône","Transportista","FR 69 / 01 / 38","3,0 ml","4,8"],["Toralta","Distribuidor","Alicante","Diaria","4,6"],["Montaverner","Distribuidor","Valencia sur","Diaria","4,5"]]},
 almacenes:{eyebrow:"WMS",title:"Almacenes",description:"Control de centros, ubicaciones, stock, inventarios físicos, movimientos y trazabilidad por código de barras.",action:"+ Nuevo inventario",stats:[],columns:["Almacén / inventario","Tráfico","Ubicaciones","Lecturas","Estado"],rows:[]},
 tracking:{eyebrow:"VISIBILIDAD",title:"Tracking",description:"Seguimiento operativo de viajes y expediciones con hitos, ETA e incidencias.",action:"Abrir mapa",stats:[],columns:["Viaje","Último hito","Ubicación","ETA","Estado"],rows:[]},
 "epod-cmr":{eyebrow:"DOCUMENTACIÓN",title:"Documentos",description:"Pruebas de entrega, firmas, fotografías, reservas y cartas de porte digitales.",action:"Subir documento",stats:[["34","POD recibidos"],["3","Pendientes de validar"],["2","Con reservas"]],columns:["Documento","Expedición","Destinatario","Recepción","Estado"],rows:[["POD-260069","EX-260069","Atlas Components","Hoy 11:45","Validado"],["CMR-260071","EX-260071","Mediterránea Retail","En tránsito","Pendiente"],["POD-260066","EX-260066","Nordic Home","Ayer 17:20","Con reserva"]]},
 informes:{eyebrow:"ANALÍTICA",title:"Informes",description:"Indicadores de servicio, rentabilidad, productividad, calidad y rendimiento de la red.",action:"+ Nuevo informe",stats:[],columns:["Informe","Periodo","Área","Actualización","Estado"],rows:[]}
} as const;

export type ModuleKey=keyof typeof modules;
export function isModuleKey(value: string): value is ModuleKey { return Object.hasOwn(modules, value); }
const createPaths:Record<ModuleKey,string>={partidas:"/dashboard/nuevo/partida",expediciones:"/dashboard/nuevo/expedicion",viajes:"/dashboard/nuevo/viaje","ofertas-tarifas":"/dashboard/registros/ofertas-tarifas/nuevo",clientes:"/dashboard/registros/clientes/nuevo",colaboradores:"/dashboard/registros/colaboradores/nuevo",almacenes:"/dashboard/registros/almacenes/nuevo",tracking:"/dashboard/tracking?vista=mapa","epod-cmr":"/dashboard/registros/epod-cmr/nuevo",informes:"/dashboard/registros/informes/nuevo"};
const unfinishedModules = new Set<ModuleKey>(["ofertas-tarifas","almacenes","tracking","informes"]);

export default function ModuleView({module,demo=false,basePath="/dashboard"}:{module:ModuleKey;demo?:boolean;basePath?:"/dashboard"|"/demo"}){
 if(!isModuleKey(module))notFound();const key=module;const data=demo?modules[key]:{...modules[key],stats:[] as readonly (readonly string[])[],rows:[] as readonly (readonly string[])[]};
 const columns=data.columns.map((label,index)=>({key:`c${index}`,label}));
 const rows=data.rows.map(row=>Object.fromEntries(row.map((value,index)=>[`c${index}`,value])));
 const rowHrefs=data.rows.map(row=>key==="viajes"?`${basePath}/viajes/${row[0]}`:key==="partidas"?`${basePath}/partidas/${encodeURIComponent(row[0])}`:key==="colaboradores"&&row[0]==="Velocity Transinternacional"?`${basePath}/colaboradores/velocity`:`${basePath}/registros/${key}/${encodeURIComponent(row[0])}`);
 const unfinished=unfinishedModules.has(key);
 return <main className={styles.shell}><section className={styles.content}><ScreenHeader eyebrow={data.eyebrow} title={data.title} description={data.description}><Link className={screenButton.secondary} href={`${basePath}/importar?entidad=${key}`}>Importar Excel</Link><Link className={screenButton.primary} href={createPaths[key].replace("/dashboard",basePath)}>{data.action}</Link></ScreenHeader>{!unfinished&&!demo&&<p role="status" style={{padding:"14px 16px",border:"1px solid #d5dee8",borderRadius:10,background:"#f7f9fb",color:"#526173",fontWeight:700}}>Todavía no hay registros reales en este módulo.</p>}{unfinished&&<p role="status" style={{padding:"14px 16px",border:"1px solid #d5dee8",borderRadius:10,background:"#f7f9fb",color:"#526173",fontWeight:700}}>Módulo en construcción. Todavía no hay datos reales conectados.</p>}<MetricGrid items={data.stats.map(([value,label])=>({label,value}))} /><section className={screenPanelClass}><DataGrid persistPreferences={basePath !== "/demo"} storageKey={key} columns={columns} rows={rows} rowHrefs={rowHrefs} searchPlaceholder={`Buscar en ${data.title.toLowerCase()}...`} /></section></section></main>;
}
